version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: playwright-test
    versions:
    - 2.0.0
    - 3.0.1
    - 3.0.5
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.2
